apiVersion: v1
<<<<<<< HEAD
appVersion: V.0.1
=======
appVersion: V1.0
>>>>>>> development
description: 'Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.'
name: vtc
version: 0.1.0
home: pc.zaakonline.nl
icon: pc.zaakonline.nl