apiVersion: v1
<<<<<<< HEAD
appVersion: V.0.1
description: 'Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.'
=======
appVersion: V1.0
description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.&#039;'
>>>>>>> development
name: vtc
version: 0.1.0
home: pc.zaakonline.nl
icon: pc.zaakonline.nl