apiVersion: v1
entries:
  vtc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-07-31T09:50:58.239571735Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: ddd7dc3d6d74bde6f42257937e72dfbef3533dcdeeac35d02c31200853ee5468
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: vtc
    urls:
    - vtc-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-31T09:50:58.234727936Z"
