apiVersion: v1
entries:
  pc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-27T09:32:58.958154085Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: a083c8983d10aa1f6bd51397e969c60002e16a670af6b584f1df199bdd826ca4
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
  vtc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-27T09:32:58.960884685Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 5126a88446f83ba60c989b4e463792af17922f5b298a5ad485860ecb91417bdc
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: vtc
    urls:
    - vtc-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-27T09:32:58.954787785Z"
