apiVersion: v1
entries:
  vtc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-09-18T14:16:23.706855179Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: e98f8c3f608f0bf5da2294de03cbec8319edb61f89bddbcc30e232340ad7fbaf
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: vtc
    urls:
    - vtc-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-18T14:16:23.699810279Z"
