apiVersion: v1
entries:
  vtc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-09-08T23:03:54.1080401Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 1f99c526fd9222db65d45b787173489a7a70c96e72387cde2bfacec0484b112c
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: vtc
    urls:
    - vtc-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-08T23:03:54.1038492Z"
