apiVersion: v1
entries:
  vtc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-26T11:56:59.5727385Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 9dc0f4c28e043f72d794150197bc5cadb4515fa6cb402eb214fccb8279f0267b
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: vtc
    urls:
    - vtc-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-26T11:56:59.5634554Z"
