apiVersion: v1
entries:
<<<<<<< HEAD
  pc:
  - apiVersion: v1
    appVersion: V.0.1
<<<<<<< HEAD
    created: "2020-07-29T07:47:59.982108937Z"
=======
    created: "2020-07-24T13:05:54.6846672Z"
>>>>>>> development
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: a3ebf537582710b118b706a276db61fec8e25b642f3e8f3d1bb239ac1131f064
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
  vtc:
  - apiVersion: v1
    appVersion: V.0.1
<<<<<<< HEAD
    created: "2020-07-29T07:47:59.995274637Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 2ceaa6d371f36ab607b4e6b6222b67b17b9529e9ad5bf454c13379cddb3667b5
=======
    created: "2020-07-24T13:05:54.6923787Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: c576ba2c85e15b6a5ae7a6077d718e650e5e5ec82c5e39d6dbf2dbaadbed164d
>>>>>>> development
=======
  vtc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-29T12:55:04.371414462Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 4ec90fd7ecaaabe0fa8072257af07b3f5d31357f3a41642509bfbc9c8243285b
>>>>>>> development
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: vtc
    urls:
    - vtc-0.1.0.tgz
    version: 0.1.0
<<<<<<< HEAD
<<<<<<< HEAD
generated: "2020-07-29T07:47:59.971491637Z"
=======
generated: "2020-07-24T13:05:54.6748062Z"
>>>>>>> development
=======
generated: "2020-07-29T12:55:04.343823562Z"
>>>>>>> development
