apiVersion: v1
entries:
  vtc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-10-16T11:29:05.2473246Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 78a65b41172595f4e954fae788211837eeffd4369b54933337e35db54377a5f8
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: vtc
    urls:
    - vtc-0.1.0.tgz
    version: 0.1.0
generated: "2020-10-16T11:29:05.241338Z"
