apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "name" . }}-warmup
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-warmup
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # this cronjob runs every 10 minutes https://crontab.guru/#*_*_*_*_*
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: dependencies
            secret:
              secretName: {{ template "fullname" . }}-dependencies
              defaultMode: 420
          containers:
          - name: {{ include "name" . }}-php
            image: "{{ .Values.php.image }}:{{ .Values.php.tag }}"
            imagePullPolicy: Always
            args:
            - bin/console 
            - app:cache:warmup
            volumeMounts:
              - mountPath: /srv/api/config/packages/dependencies.yaml
                subPath: dependencies.yaml
                name: dependencies
                readOnly: true
            env:
              - name: JWT_SECRET_KEY
                value: '%kernel.project_dir%/config/jwt/private.pem'
              - name: JWT_PUBLIC_KEY
                value: '%kernel.project_dir%/config/jwt/public.pem'
              - name: JWT_PASSPHRASE
                value: 'bafe1dc254b45471754c221081f874aa'
              - name: APP_ENV
                value: 'prod'
              - name: TRUSTED_HOSTS
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "fullname" . }}
                    key: trusted-hosts
              - name: TRUSTED_PROXIES
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "fullname" . }}
                    key: trusted-proxies
              - name: APP_VERSION
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "fullname" . }}
                    key: app-version
              - name: APP_DEBUG
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "fullname" . }}
                    key: debug
              - name: APP_CACHE
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "fullname" . }}
                    key: cache
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: {{ template "fullname" . }}
                    key: database-url
              - name: CORS_ALLOW_ORIGIN
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "fullname" . }}
                    key: app-corsAllowOrigin
              - name: APP_APPLICATION_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ template "fullname" . }}
                    key: app_application_key
              {{ if .Values.redis.enabled }}
              - name: REDIS_HOST
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "fullname" . }}
                    key: redis-host
              - name: REDIS_PORT
                valueFrom:
                  configMapKeyRef:
                    name: {{ template "fullname" . }}
                    key: redis-port
              {{- end }}
              - name: APP_URL
                valueFrom:
                  configMapKeyRef:
                    key: url
                    name: {{ template "fullname" . }}
          restartPolicy: OnFailure
